version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=notes
    volumes:
      - ./app/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

